  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  data:
    build: docker/blocks/loki/data
    command: node /home/node/data.js http://loki:3100
    depends_on:
      - loki
    # when loki starts, there might be some time while it is not
    # accepting requests, so we allow data.js to fail a couple times
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 20 # should be enough